spring.cloud.gcp:
  config.enabled: false
  sql:
    database-name: actor
    instance-connection-name: cedar-card-400213:europe-west2:actor-pgsql

spring:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        default_schema: ${AF_ACTOR_FINDER_DB_SCHEMA:public}
  datasource:
    username: postgres
    password: actor-pgsql
    hikari.maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/0-changelog-master-v1.0.xml
    parameters:
      schema: ${spring.jpa.properties.hibernate.default_schema}

cloud:
  random.number:
    22

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    diskspace:
      enabled: false

pubsub:
  project-id: cedar-card-400213
  stats-topic: actor-stats-local
  event-topic: event-bus-local

weather:
  city:
    name: Yerevan
    lat: 40.1872
    lng: 44.5152
    currentWeather: true
    hourly: temperature_2m,relativehumidity_2m,windspeed_10m

api-connector-service:
  url: localhost:8089

#liquibase:
#  enabled: true
#  drop-first: false
#  change-log: classpath:db/changelog/0-changelog-master-v1.0.xml
#  default-schema: public