runtime: java17
service: api-connector-service
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: cedar-card-400213@appspot.gserviceaccount.com

env_variables:
  spring_profiles_active: "cloud"