server:
  port: 8085

spring.cloud.gcp:
  config.enabled: false
  sql:
    database-name: actor
    instance-connection-name: cedar-card-400213:europe-west2:actor-pgsql

spring:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        default_schema: ${AF_ACTOR_FINDER_DB_SCHEMA:read_model}
    show-sql: true
  datasource:
    username: postgres
    password: actor-pgsql
    hikari.maximum-pool-size: 2
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/0-changelog-master-v1.0.xml
    parameters:
      schema: ${spring.jpa.properties.hibernate.default_schema}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    diskspace:
      enabled: false

pubsub:
  project-id: cedar-card-400213
  sub-id: event-bus-local-sub
  event-topic: event-bus-local


#liquibase:
#  enabled: true
#  drop-first: false
#  change-log: classpath:db/changelog/0-changelog-master-v1.0.xml
#  default-schema: public